### ISSUE TITLE
Finalize Set collection type

### ISSUE THREAD

**Issue by nand4011** [momentohq/client-sdk-java#245]
- Audit the set methods against the .NET SDK.
- Ensure consistent naming for fields, values, elements, etc. is used.
- Ensure that methods that take a collection take the most general collection that makes sense.
- Ensure that methods that take a collection behave in an expected way when given an empty collection.
- Only @Nullable annotate arguments if there isn't a signature that leaves it out. If there isn't, check if there should be.

**Comment by malandis** [comment]
✅ nullable annotations: https://github.com/momentohq/client-sdk-java/issues/245

**Comment by malandis** [comment]
✅ use iterables: https://github.com/momentohq/client-sdk-java/pull/278
✅ audit coverage vs other SDKs

**Comment by malandis** [comment]
✅ audit response types
