### ISSUE TITLE
Audit nullable annotations

### ISSUE THREAD

**Issue by malandis** [momentohq/client-sdk-java#261]
In the client API, we mark some arguments as nullable (notnullable). Others like `cacheName`, collection name, etc are not annotated all together. Audit the arguments across the board this.

**Comment by cprice404** [comment]
@malandis  : @nand4011 and I have discussed this and I think we are leaning toward removing most of them for now.  You should touch base with him before you do any work on this front.

**Comment by malandis** [comment]
We decided to use annotations across the top level API.
